include(GoogleTest)

macro(package_add_test SOURCE_FILE)
    string(REGEX REPLACE "\.[^.]*$" "" TESTNAME "${SOURCE_FILE}")
    add_executable(${TESTNAME} ${SOURCE_FILE})
    target_link_libraries(${TESTNAME} PRIVATE GTest::gtest_main tire-impl)
    gtest_discover_tests(${TESTNAME})
endmacro()

package_add_test(colortest.cpp)
package_add_test(databasetest.cpp)
package_add_test(enumnamestest.cpp)
package_add_test(periodtest.cpp)
package_add_test(plantest.cpp)
package_add_test(projecteditortest.cpp)
package_add_test(sqlvaluetest.cpp)
package_add_test(timesheetrepositorytest.cpp)
package_add_test(undostacktransactiontest.cpp)
